---
sudo: false
language: ruby
bundler_args: --without development system_tests --full-index
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
script: bundle exec rake test
env:
  - PUPPET_GEM_VERSION="~> 3.8.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_GEM_VERSION="~> 4.9.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 4.10.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 5.0.0" STRICT_VARIABLES=yes
matrix:
  exclude:
  # Ruby 1.9.3
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 4.9.0"
  # Ruby 2.0.0
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 4.9.0"
  # Ruby 2.1.0
  # Ruby 2.2.0
  # Ruby 2.3.0
